x-veld:
  code:
    description: "custom evaluation logic on fasttext word embeddings."
    topic:
      - "NLP"
      - "Machine learning"
      - "evaluation"

    input:
      - volume: /veld/input/model/
        environment_var: in_model_file
        file_type: "fasttext model"
        content:
          - "NLP model"
          - "word embeddings model"
      - volume: /veld/input/model/
        environment_var: in_model_metadata_file
        file_type: "yaml"
        content: "metadata"
      - volume: /veld/input/eval_data/
        environment_var: in_eval_gold_data_file
        file_type: "yaml"
        content: "NLP gold data"

    output:
      - volume: /veld/output/summary/
        environment_var: out_eval_summary_file
        file_type: "yaml"
        description: ""
      - volume: /veld/output/log/
        environment_var: out_eval_log_file
        file_type: "txt"
        content: "logs"

services:
  veld_eval_fasttext:
    build: 
      context: .
      dockerfile: ./build_fasttext.dockerfile
    command: python eval_fasttext.py
    volumes:
      - ./src/:/veld/code/:z
    environment:
      in_model_file: null
      in_model_metadata_file: null
      in_2_eval_gold_data_file: null
      out_1_eval_summary_file: null
      out_2_eval_log_file: null

